### ISSUE TITLE
Long names assertions

### ISSUE THREAD

**Issue by ichavchavadze** [lsfusion/platform#1037]
If properties have very long name, there are assertions: 

*stacks for 5.2-SNAPSHOT, but bug exists also in 6.0-SNAPSHOT

1. First case:

```
NAMESPACE LongInternationalizationNamespace;
CLASS LongInternationalizationClass;
longInternationalizationProperty1 = DATA STRING(LongInternationalizationClass);
longInternationalizationProperty2 = DATA STRING(LongInternationalizationClass);
```

```
java.lang.AssertionError
	at lsfusion.base.col.implementations.abs.AMSet.exclAdd(AMSet.java:13)
	at lsfusion.base.col.implementations.abs.ASet.addExcl(ASet.java:138)
	at lsfusion.server.physics.exec.db.table.ImplementTable.addField_aroundBody2(ImplementTable.java:177)
	at lsfusion.server.physics.exec.db.table.ImplementTable.addField_aroundBody3$advice(ImplementTable.java:13)
	at lsfusion.server.physics.exec.db.table.ImplementTable.addField(ImplementTable.java:1)
	at lsfusion.server.logics.property.Property.initStored(Property.java:1159)
```

2. Second case:
```
NAMESPACE LongInternationalizationNamespace;
CLASS InternationalizationClass1;
CLASS InternationalizationClass2;
internationalizationProperty1 = DATA STRING(InternationalizationClass1);
internationalizationProperty2 = DATA STRING(InternationalizationClass2);
```

```
java.lang.AssertionError
	at lsfusion.server.physics.exec.db.controller.manager.DBManager.migrateClassProperties(DBManager.java:2200)
	at lsfusion.server.physics.exec.db.controller.manager.DBManager.alterDBStructure(DBManager.java:2301)
	at lsfusion.server.physics.exec.db.controller.manager.DBManager.synchronizeDB(DBManager.java:1413)
	at lsfusion.server.physics.exec.db.controller.init.SynchronizeDBTask.run(SynchronizeDBTask.java:17)
```

**Comment by danchanka** [comment]
Fixed in version 6. Informative error messages are now displayed.

**Comment by danchanka** [comment]
Fixed in version 6. Informative error messages are now displayed.
