### ISSUE TITLE
Assert on enlarging column 'forbidDuplicateForms'

### ISSUE THREAD

**Issue by ichavchavadze** [lsfusion/platform#1101]
`assert equals(flexes[i], 0.0);` in calculateFlexes 

Form securityPolicy, when enlarging property dataForbidDuplicateForms

```
Caused by: java.lang.AssertionError
    at Unknown.ff_g$(Throwable.java:62)
    at Unknown.hUf_g$(Error.java:26)
    at Unknown.nUf_g$(AssertionError.java:23)
    at Unknown.xji_g$(GwtClientUtils.java:943)
    at Unknown.Oul_g$(GGridPropertyTable.java:527)
    at Unknown.eUl_g$(GGridPropertyTable.java:212)
    at Unknown.yDi_g$(ResizeHandler.java:205)
    at Unknown.xDi_g$(ResizeHandler.java:194)
    at Unknown.H9d_g$(Event.java:195)
    at Unknown.G9d_g$(Event.java:194)
    at Unknown.sTc_g$(GwtEvent.java:76)
    at Unknown.K3c_g$(EventBus.java:40)
    at Unknown.o4c_g$(SimpleEventBus.java:193)
    at Unknown.u4c_g$(SimpleEventBus.java:88)
    at Unknown.a4c_g$(HandlerManager.java:127)
    at Unknown.I9d_g$(Event.java:87)
    at Unknown.k9d_g$(Event.java:480)
    at Unknown.w7d_g$(DOM.java:1458)
    at Unknown.cde_g$(DOMImplStandard.java:350)
    at Unknown.ohb_g$(Impl.java:299)
    at Unknown.rhb_g$(Impl.java:351)
    at Unknown.anonymous(Impl.java:78)
```

**Comment by ichavchavadze** [comment]
Already resolved (can't reproduce)
