### ISSUE TITLE
NPE when using WINDOW instruction with MENU type without specifying orientation

### ISSUE THREAD

**Issue by danchanka** [lsfusion/platform#562]
Null pointer exception when using sample from [documentation](https://documentation.lsfusion.org/pages/viewpage.action?pageId=3670087):

    // menu without scrollbars under the root window
    WINDOW menu MENU HIDESCROLLBARS DRAWROOT POSITION(20, 6, 80, 4); 

```
java.lang.NullPointerException
	at lsfusion.server.language.ScriptingLogicsModule.createMenuWindow(ScriptingLogicsModule.java:4368)
	at lsfusion.server.language.ScriptingLogicsModule.addScriptedWindow(ScriptingLogicsModule.java:4340)
	at lsfusion.server.language.LsfLogicsParser.windowCreateStatement(LsfLogicsParser.java:31214)
	at lsfusion.server.language.LsfLogicsParser.windowStatement(LsfLogicsParser.java:31150)
```
We need to set a default value to the orientation in this case or forbid use of `MENU` type without orientation specification. It seems there can be similar problems with other window options.

**Comment by danchanka** [comment]
No longer relevant due to the absence of MENU type.
