### ISSUE TITLE
support compiled by jdk 17 ? support undetow

### ISSUE THREAD

**Issue by coeove** [lsfusion/platform#953]
support compiled by jdk 17 ?
.0.7+7/bin/java -cp .:./*:./lsfusion-server-6.0.jar -Ddb.user=postgres -Ddb.name=lsfusion -Ddb.server=localhost:5432 -Ddb.password=11111 lsfusion.server.logics.BusinessLogicsBootstrap
17 Jun 2023 20:56:18,162  INFO StartLogger - Server is starting...
17 Jun 2023 20:56:19,154  INFO StartLogger - Logics instance is starting...
17 Jun 2023 20:56:19,223  INFO StartLogger - Initializing BusinessLogics
17 Jun 2023 20:56:19,236  INFO StartLogger - Initializing string literals data
17 Jun 2023 20:56:19,236  INFO StartLogger - Creating modules
17 Jun 2023 20:56:19,244  INFO StartLogger - Initializing localizer
17 Jun 2023 20:56:20,323  INFO StartLogger - Initializing dependencies
17 Jun 2023 20:56:20,482  INFO StartLogger - Initializing modules order
17 Jun 2023 20:56:20,489 ERROR StartLogger - Exception while starting logics instance: 
java.lang.RuntimeException: [error]:	module 'Icon' has already been added
	at lsfusion.server.physics.dev.module.ModuleList.fillNameToModules(ModuleList.java:234)
	at lsfusion.server.logics.BusinessLogics.initModuleOrders(BusinessLogics.java:409)
	at lsfusion.server.physics.dev.module.controller.init.InitModuleOrderTask.run(InitModuleOrderTask.java:13)
	at lsfusion.server.base.task.Task.proceed(Task.java:154)
	at lsfusion.server.base.task.Task$1.aspectRun(Task.java:112)
	at lsfusion.server.base.controller.thread.ExecutorFactory$AspectRunnable.run(ExecutorFactory.java:475)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at lsfusion.server.base.controller.thread.ExecutorFactory$ClosableDaemonThreadFactory$ClosableThread.run(ExecutorFactory.java:554)
17 Jun 2023 20:56:20,493  INFO StartLogger - Error starting server, server will be stopped.
17 Jun 2023 20:56:20,493  INFO StartLogger - Server is stopping...
17 Jun 2023 20:56:20,501  INFO StartLogger - Logics instance is stopping...
17 Jun 2023 20:56:20,502  INFO StartLogger - Logics instance has stopped...
17 Jun 2023 20:56:20,507  INFO StartLogger - Server has stopped...

**Comment by coeove** [comment]
`
keytool -genkey -keystore YourKeyStoreFileAtPojectDirectory -storepass YourPassStoreString -keyalg rsa -alias YourKeyString -keypass YourPassKeyString -validity 99999 -dname "cn=XXYYZZ, o=XXYYZZ, l=YourCity, S=YourState, c=YourCountry"
`

**Comment by coeove** [comment]
.0.7+7/bin/java -cp .:./*:./lsfusion-server-6.0.jar -Ddb.user=postgres -Ddb.name=lsfusion -Ddb.server=localhost:5432 -Ddb.password=11111 lsfusion.server.logics.BusinessLogicsBootstrap
17 Jun 2023 20:56:18,162  INFO StartLogger - Server is starting...
17 Jun 2023 20:56:19,154  INFO StartLogger - Logics instance is starting...
17 Jun 2023 20:56:19,223  INFO StartLogger - Initializing BusinessLogics
17 Jun 2023 20:56:19,236  INFO StartLogger - Initializing string literals data
17 Jun 2023 20:56:19,236  INFO StartLogger - Creating modules
17 Jun 2023 20:56:19,244  INFO StartLogger - Initializing localizer
17 Jun 2023 20:56:20,323  INFO StartLogger - Initializing dependencies
17 Jun 2023 20:56:20,482  INFO StartLogger - Initializing modules order
17 Jun 2023 20:56:20,489 ERROR StartLogger - Exception while starting logics instance: 
java.lang.RuntimeException: [error]:	module 'Icon' has already been added
	at lsfusion.server.physics.dev.module.ModuleList.fillNameToModules(ModuleList.java:234)
	at lsfusion.server.logics.BusinessLogics.initModuleOrders(BusinessLogics.java:409)
	at lsfusion.server.physics.dev.module.controller.init.InitModuleOrderTask.run(InitModuleOrderTask.java:13)
	at lsfusion.server.base.task.Task.proceed(Task.java:154)
	at lsfusion.server.base.task.Task$1.aspectRun(Task.java:112)
	at lsfusion.server.base.controller.thread.ExecutorFactory$AspectRunnable.run(ExecutorFactory.java:475)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at lsfusion.server.base.controller.thread.ExecutorFactory$ClosableDaemonThreadFactory$ClosableThread.run(ExecutorFactory.java:554)
17 Jun 2023 20:56:20,493  INFO StartLogger - Error starting server, server will be stopped.
17 Jun 2023 20:56:20,493  INFO StartLogger - Server is stopping...
17 Jun 2023 20:56:20,501  INFO StartLogger - Logics instance is stopping...
17 Jun 2023 20:56:20,502  INFO StartLogger - Logics instance has stopped...
17 Jun 2023 20:56:20,507  INFO StartLogger - Server has stopped...

**Comment by CrushBy** [comment]
The error with your log appears not at the compile stage, but at the startup stage. The problem is that your Icon.lsf file (the Icon module) ends up in the classpath twice. Apparently, once inside lsfusion-server-6.0.jar and once in working directory (.) or inside some jar which is in working directory (./*).

You have two options to work with the platform: with sources (if you want to change them), or with already built jar files of the platform (lsfusion-server-6.0.jar). Which is your case ?

**Comment by coeove** [comment]
desktop-client support compiled by jdk  17 ? 
the code  framework need recreate by maven!

**Comment by pavel-miniutka** [comment]
> desktop-client support compiled by jdk 17 ? the code framework need recreate by maven!

Yes, desktop-client supports compilation with jdk 17. Could you please provide any text of the error you receive?

**Comment by ichavchavadze** [comment]
Our team has requested additional information which was not provided. This issue is closed, but you can still provide the requested data by leaving a comment.
